# Generated by Django 3.2.10 on 2021-12-29 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='create_at',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shopping', 'sh_p'), ('wishing', 'wh_p')], default='wishing', max_length=8),
        ),
    ]
