# Generated by Django 3.2.10 on 2022-01-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shoplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('wh_p', 'wishing'), ('sh_p', 'shopping')], default='wh_p', max_length=8),
        ),
    ]
